- name: install Golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: App Pre-Req
  ansible.builtin.include_tasks: "app-prereq.yml"

#- name: download and install dependencies
  #ansible.builtin.shell:
  #"changed": true, "cmd": "go init dispatch; go get ; go build"
  #args:
    #chdir: /app
    #cmd: go init dispatch; go get ; go build

- name: download and install dependencies
  ansible.builtin.shell:
    chdir: /app
    cmd: go init dispatch; go get ; go build

- name: SystemD Setup
  ansible.builtin.include_tasks: "systemd.yml"



