- name: install Golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: App Pre-Req
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: download and install dependencies
  ansible.builtin.yum:
    name: go init dispatch; go get; go build
    state: installed

- name: SystemD Setup
  ansible.builtin.include_tasks: "systemd.yml"



